site_name: Apollo 11
site_url: https://darshanraul.io/apollo11
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    - primary: deep orange
    # Palette toggle for light mode
    - scheme: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - navigation.top


nav:
  - Home: index.md
  - Liftoff: stages/liftoff/liftoff.md
  - stage-1: stages/stage-1/stage-1.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format