apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: kub
spec:
  selector:
    matchLabels:
      app: kub
  replicas: 3
  template:
    metadata:
      labels:
        app: kub
    spec:
      containers:
      - name: kub
        image: fast-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
  labels:
    app: kub
spec:
  type: LoadBalancer
  selector:
    app: kub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
