version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306 # use custom port if already have mysql running on your machine
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  # adminer_container: ## not needed if using any local gui tool eg. vscode,
  #   image: adminer:latest
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql_db_container
  #   ports:
  #     - 8080:8080
  app:
    container_name: app
    build: .
    command: bash -c "uvicorn index:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - mysql_db_container
volumes:
  mysql_db_data_container:
